//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRXS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserTrueName { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Com { get; set; }
        public string Address { get; set; }
        public string Shen { get; set; }
        public string Shi { get; set; }
        public string Qu { get; set; }
        public string Xian { get; set; }
    }
}
