//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRXS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficFee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IDCard { get; set; }
        public string OutReason { get; set; }
        public string CollectionNum { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string WorkMan { get; set; }
        public string AccountName { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
        public string BZ1 { get; set; }
        public string BZ2 { get; set; }
        public string BZ3 { get; set; }
        public string BZ4 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string IsPass { get; set; }
    }
}
